spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp


spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://43.201.56.116:3306/csh_final?serverTimezone=UTC&characterEncoding=UTF-8
#spring.datasource.username=soohyunoc
#spring.datasource.password=oc5029oc

spring.datasource.url=jdbc:mariadb://3.36.28.140:3306/csh_final?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=jmcoding
spring.datasource.password=123qwe!


mybatis.type-aliases-package=com.my.csh_boot.vo

mybatis.mapper-locations=classpath:com/my/csh_boot/mapper/*.xml